version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      RAW_INPUT_PATH: /app/worker
      RAW_OUTPUT_PATH: /app/worker
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

volumes:
  postgres_data:
